---

resources:
- name: every-5m
  type: time
  source: {interval: 5m}

- name: git-repo
  type: git
  source:
    uri: https://github.com/KamenRusev/Hello-Concourse.git
    branch: main

jobs:
- name: job-every-5m
  plan:
  - get: every-5m
    trigger: true
  - get: git-repo
    trigger: true
  - task: simple-task-every-5m
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      inputs:
        - name: git-repo
      run:
        path: sh
        args: ["git-repo/scripts/test_script.sh"]