
---

resources:
- name: every-5m
  type: time
  source: {interval: 5m}

- name: test_script
  type: git
  source:
    uri: https://github.com/KamenRusev/Hello-Concourse.git
    branch: main

jobs:
- name: job-every-5m
  plan:
  - get: every-5m
    trigger: true
  - task: simple-task-every-5m
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello SAP"]

- name: test_script
  plan:
  - get: test_script
    trigger: true
  - task: run_test_script
    file: test_script/test_script.yml
